version: '3'

services:
  milvus:
    image: milvusdb/milvus:latest
    ports:
      - "19530:19530"
    volumes:
      - ./volumes/milvus:/var/lib/milvus

  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379:2379"
    volumes:
      - ./volumes/etcd:/etcd-data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./volumes/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
